### ISSUE TITLE
Testing the reproduction flow

### ISSUE THREAD

**Issue by andkov** [benmarwick/mjbtramp#2]
@benmarwick , 
  I like your approach to reproducible publications and see a great deal of things to learn from this example. The neat Word document emerging at the end of the pipeline is worth a particular mention and a careful study. 

A few comments. 

A) I've just successfully reproduced the paper.

``` r
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.1.0 magrittr_1.5 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6      tidyr_0.6.0      dplyr_0.5.0      assertthat_0.1  
 [5] grid_3.3.1       plyr_1.8.4       R6_2.1.3         gtable_0.2.0    
 [9] DBI_0.5          scales_0.4.0     highr_0.6        lazyeval_0.2.0  
[13] testit_0.5       tools_3.3.1      readr_1.0.0      munsell_0.4.3   
[17] colorspace_1.2-6 knitr_1.14       tibble_1.2     
```

B)

> First is the packrat directory, which contains the source code for all the packages we depend on. If all works well, these will be installed on your computer when you open `mjbtramp.Rproj` in RStudio. 

All did work well, as seen from A). I like the solution of placing the dependencies in `./packrat/src` and checking the installation at the opening of the `.Rproj`.  This is particularly important if relying on packages that are still in active development.  Just to report, I was asked to install the following packages before the documents could be knitted ( In case, you would like to add them to the `./packrat/src` to further smoothen an already stable reproduction) : 
- `bookdown`
- `readxl`
- `ggrepel`
- `perm`
- `purrr`
- `broom`

**Comment by benmarwick** [comment]
Thanks for your kind note, and for taking the compendium for a test run! I'm delighted that it basically worked as intended for you (phew!). If you have any similar compendium-type repositories, I'd be glad to have a look, I'm always looking to see how others are tackling these issues about reproducibility, tooling, etc. 

That's interesting that you had to install those six packages. I can see them listed in my [`packrat.lock`](https://github.com/benmarwick/mjbtramp/blob/master/packrat/packrat.lock) and the  packrat [`src`](https://github.com/benmarwick/mjbtramp/tree/master/packrat/src) directory already, so it's unexpected that you'd be prompted to download them. I'll have a look into why that might have happened to you. They should have been installed along with the others. I'm finding that packrat is still a bit unreliable and does odd things like this from time to time. But it's improved to the point where I can use it daily, and I'm optimistic that it'll keep getting better. 

About your part A), I see your session info there, but I 'm not sure how that shows you successfully reproduced the paper. All it shows is your session info, which would look the same even if you hadn't rendered the Rmd to Word. One way to show that you'd  successfully reproduced the paper might be to add a screenshot of the markdown console, like this:

![clipboard02](https://cloud.githubusercontent.com/assets/1262179/18442125/6362d22e-78c4-11e6-975a-08010cf74cd3.png)
